### ISSUE TITLE
Generate documentation

### ISSUE THREAD

**Issue by chriszs** [tvkitchen/meta#8]
Per @reefdog:
>We should probably be generating docs but I do think this is fine until we are!

Auto-generated docs tend to be unfriendly, but so long as we're using JSDoc, it might be good to start auto-generating the friendliest-looking doc pages we can in part so we can try to understand how the API will play to external audiences and catch issues now (like how issues with drafts are often caught in proofs). Could provide the basis/go along with more curated docs later.

**Comment by slifty** [comment]
hey hey hey but what about this way more impressive origin story:

> "maybe I shouldn't actually try to document things here, and instead we should be generating documentation"
> `- @slifty `

*shakes fist at @reefdog*

actually though thank you for making the issue!

I like the thinking of "auto generate as first step, move to manual over time" -- and the manual can come after we finish our brand language / as part of the website design.

One note about timing: I wouldn't want the auto-documentation to take a major effort just yet since I do think having the caption generation milestone knocked out takes priority.

**Comment by reefdog** [comment]
I don't recall that origin story _at all_.

**Comment by chriszs** [comment]
Looks like a good way to do this before we have a final website would be to include a [jsdoc-to-markdown](https://github.com/jsdoc2md/jsdoc-to-markdown) script and have us generate API docs in the docs folder for anything with a JSDoc change.
